#+TITLE: Emacs Configuration File
#+AUTHOR: Rabi Ahmad
#+DESCRIPTION: Rabi's personal Emacs configuration file

* Note
GNU Emacs 29.4 configuration in org-mode for better readability and maintainability.
Tailored for Windows 11. No guarantee that this will work on any other system.
* Usage
To use this configuration there must be an ~/.emacs.d/ directory set up which will contain the early-init.el and init.el. Those files do not need to be created manually.
Steps:
1. open this org file in Emacs
2. Run `C-c C-v C-t`. This will "tangle" the code blocks from the configuration into the relevant init files. This essentially parses the code blocks using Org Babel and copies them to the the emacs configuration files.
* Configuration
** Built-Ins
Going to configure all the built in packages first
And any third party lib that are related to it will go under them.
*** Startup performance
Make startup faster by reducing the frequency of garbage collection and then use a hook to measure Emacs startup time. Also, turn on lexical-binding for the init file.
#+begin_src emacs-lisp :tangle "~/.emacs.d/config.el" :mkdirp yes
;; -*- lexical-binding: t; -*-

;; The default is 800 kilobytes.  Measured in bytes.
(setq gc-cons-threshold (* 50 1000 1000))

;; Profile emacs startup
(add-hook 'emacs-startup-hook
          (lambda ()
            (message "*** Emacs loaded in %s seconds with %d garbage collections."
                     (emacs-init-time "%.2f")
                     gcs-done)))
#+end_src
*** Server mode
Start the Emacs server from this instance so that all emacsclient calls are routed here.
#+begin_src emacs-lisp :tangle "~/.emacs.d/config.el" :mkdirp yes
(server-start)
#+end_src
*** UTF-8 encoding
The main purpose here is because the encoding of icons was not working on Windows 11, so this had to be changed to UTF-8 in order for nerd-icons to display correctly.

Issues with Windows 11 not displaying icons correctly
Github Issue: https://github.com/emacs-dashboard/emacs-dashboard/issues/471
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(set-language-environment "UTF-8")  ; char-displayable-p returns 'unicode
(set-language-environment "English")  ; char-displayable-p returns nil
(prefer-coding-system 'utf-8)
#+end_src
*** UI elements
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(scroll-bar-mode -1)     ; Disable scroll bar
(tool-bar-mode -1)       ; Disable toolbar
(tooltip-mode -1)        ; Disable tooltips
(set-fringe-mode 10)     ; Give more breathing room
(toggle-frame-maximized) ; Maximize the emacs window on startup
(set-frame-parameter nil 'alpha-background 10) ; For current frame, transparency
(add-to-list 'default-frame-alist '(alpha-background . 100)) ; For all new frames henceforth
(menu-bar-mode -1) ; Disable the menu bar
(delete-selection-mode 1)    ;; You can select text and delete it by typing.
(electric-indent-mode -1)    ;; Turn off the weird indenting that Emacs does by default.

(electric-pair-mode 1)       ;; Turns on automatic parens pairing
;; The following prevents <> from auto-pairing when electric-pair-mode is on.
;; Otherwise, org-tempo is broken when you try to <s TAB...
(add-hook 'org-mode-hook (lambda ()
  (setq-local electric-pair-inhibit-predicate
	  `(lambda (c) (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c))))))

(global-auto-revert-mode t)  ;; Automatically show changes if the file has changed
(global-visual-line-mode t)  ;; Enable truncated lines
(setq org-edit-src-content-indentation 0) ;; Set src block automatic indent to 0 instead of 2.
(setq use-file-dialog nil)   ;; No file dialog
(setq use-dialog-box nil)    ;; No dialog box
(setq pop-up-windows nil)    ;; No popup windows
(setq initial-scratch-message "")  ; Make *scratch* buffer blank
(setq use-short-answers t)  ; y-or-n-p makes answering questions faster
 (global-hl-line-mode 1)  ; Highlight the current line to make it more visible
(setq-default frame-title-format '("%b"))    ; Make window title the buffer name
(setq confirm-kill-processes nil)            ; Stop confirming the killing of processes
#+end_src
*** Disable the annoying bell sound
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (setq visible-bell 1)
#+end_src
*** Save ~ files and other backups all together
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (setq backup-directory-alist '(("." . "~/.emacs.d/backup"))
        backup-by-copying t    ; Don't delink hardlinks
        version-control t      ; Use version numbers on backups
        delete-old-versions t  ; Automatically delete excess backups
        kept-new-versions 20   ; How many of the newest versions to keep
        kept-old-versions 5)   ; And how many of the old
#+end_src
*** Line numbers
First, enable line numbers globally by default
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (column-number-mode) ; Allow display of line number
  (global-display-line-numbers-mode t) ; Activate display of line number
#+end_src

Disable line numbers for some modes
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  eshell-mode-hook
                  shell-mode-hook
                  vterm-mode-hook
                  treemacs-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src

Not too sure what this bit does. I copied it from somewhere
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (dolist (mode '(org-mode-hook
                  python-mode-hook
                  c-mode-hook
                  c++-mode-hook))
    (add-hook mode (lambda () (visual-line-mode 1))))
#+end_src
*** Initialising package sources
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (require 'package)
  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")
                           ("gnu-devel" . "https://elpa.gnu.org/devel/")))

  (unless package-archive-contents
    (package-refresh-contents))

  ;; Initialize use-package on non-Linux platform
  (unless (package-installed-p 'use-package) ; use-package not installed by default
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src
*** Auto-reverting changed buffers
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
;; Revert Dired and other buffers
(setq global-auto-revert-non-file-buffers t)

;; Revert buffers when the underlying file has changed
(global-auto-revert-mode 1)
#+end_src
** Third party packages
*** Counsel
Counsel is a collection of Ivy-enhanced versions of common Emacs commands.
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package counsel
  :bind (("M-x" . counsel-M-x)
	 ("C-x b" . counsel-ibuffer)
	 ("C-x C-b" . counsel-ibuffer)
	 ("C-x C-f" . counsel-find-file)
	 ("C-x f" . counsel-find-file)))
#+end_src
*** Ivy
Ivy is a generic completion mechanism for Emacs.
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done))
    :config
    (ivy-mode 1))
#+end_src

Use ivy-rich, a third party add-on to ivy, to provide command descriptions
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
 (use-package ivy-rich
  :init
  (ivy-rich-mode 1))
#+end_src
*** Helpful
Package to provide help iterface containing more context
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (use-package helpful
    :ensure t
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))
#+end_src
*** Window Management
**** Windmove
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
   (require 'windmove)

  ;;;###autoload
  (defun buf-move-up ()
    "Swap the current buffer and the buffer above the split.
  If there is no split, ie now window above the current one, an
  error is signaled."
  ;;  "Switches between the current buffer, and the buffer above the
  ;;  split, if possible."
    (interactive)
    (let* ((other-win (windmove-find-other-window 'up))
           (buf-this-buf (window-buffer (selected-window))))
      (if (null other-win)
          (error "No window above this one")
        ;; swap top with this one
        (set-window-buffer (selected-window) (window-buffer other-win))
        ;; move this one to top
        (set-window-buffer other-win buf-this-buf)
        (select-window other-win))))

  ;;;###autoload
  (defun buf-move-down ()
  "Swap the current buffer and the buffer under the split.
  If there is no split, ie now window under the current one, an
  error is signaled."
    (interactive)
    (let* ((other-win (windmove-find-other-window 'down))
           (buf-this-buf (window-buffer (selected-window))))
      (if (or (null other-win)
              (string-match "^ \\*Minibuf" (buffer-name (window-buffer other-win))))
          (error "No window under this one")
        ;; swap top with this one
        (set-window-buffer (selected-window) (window-buffer other-win))
        ;; move this one to top
        (set-window-buffer other-win buf-this-buf)
        (select-window other-win))))

  ;;;###autoload
  (defun buf-move-left ()
  "Swap the current buffer and the buffer on the left of the split.
  If there is no split, ie now window on the left of the current
  one, an error is signaled."
    (interactive)
    (let* ((other-win (windmove-find-other-window 'left))
           (buf-this-buf (window-buffer (selected-window))))
      (if (null other-win)
          (error "No left split")
        ;; swap top with this one
        (set-window-buffer (selected-window) (window-buffer other-win))
        ;; move this one to top
        (set-window-buffer other-win buf-this-buf)
        (select-window other-win))))

  ;;;###autoload
  (defun buf-move-right ()
  "Swap the current buffer and the buffer on the right of the split.
  If there is no split, ie now window on the right of the current
  one, an error is signaled."
    (interactive)
    (let* ((other-win (windmove-find-other-window 'right))
           (buf-this-buf (window-buffer (selected-window))))
      (if (null other-win)
          (error "No right split")
        ;; swap top with this one
        (set-window-buffer (selected-window) (window-buffer other-win))
        ;; move this one to top
        (set-window-buffer other-win buf-this-buf)
        (select-window other-win))))
#+end_src

Now set keybindings for buf-move functions
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(global-set-key (kbd "<C-S-M-up>")     'buf-move-up)
(global-set-key (kbd "<C-S-M-down>")   'buf-move-down)
(global-set-key (kbd "<C-S-M-left>")   'buf-move-left)
(global-set-key (kbd "<C-S-M-right>")  'buf-move-right)
#+end_src
*** Theme customisations
**** Fonts
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
;; Set the font everywhere
(set-frame-font "JetBrains Mono-12" nil t)

;; Check if Nerd Font is installed and avoid installation prompt
(if (member "JetBrains Mono" (font-family-list))
    (message "Nerd Font is installed")
  (message "Nerd Font is NOT installed"))

;; Set the unicode font
(setq doom-unicode-font (font-spec :family "JetBrains Mono" :size 11))

(set-face-attribute 'default nil :height 120)  ;; Adjust font size to 12 points
#+end_src
**** Highlight TODO
Add highlighting to TODO and other related keywords.
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package hl-todo
  :hook ((org-mode . hl-todo-mode)
         (prog-mode . hl-todo-mode))
  :config
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces
        `(("TODO"       warning bold)
          ("FIXME"      error bold)
          ("HACK"       font-lock-constant-face bold)
          ("REVIEW"     font-lock-keyword-face bold)
          ("NOTE"       success bold)
          ("DEPRECATED" font-lock-doc-face bold))))
#+end_src
**** Doom themes
Using the doom-dracula theme
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package doom-themes
  ;;:ensure t
  :config
  ;; Global settings (defaults)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  (load-theme 'doom-dracula t)
  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)
  ;; Enable custom neotree theme (all-the-icons must be installed!)
  (doom-themes-neotree-config)
  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config))
#+end_src
**** Icon packs
Installing all-the-icons and nerd-icons
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package all-the-icons
  :if (display-graphic-p))

(use-package nerd-icons)

(use-package nerd-icons-dired
  :hook
  (dired-mode . nerd-icons-dired-mode)
  :config
  (setq dired-listing-switches "-agho --group-directories-first"
	dired-omit-files "^\\.[^.].*"
	dired-omit-verbose nil
	dired-dwim-target t ; Copy and move files netween dired buffers
	dired-recursive-copies 'always ; "always" means no asking
	dired-recursive-deletes 'top   ; "top" means ask once for top level directory
	dired-ls-F-marks-symlinks t ; -F marks links with @
	dired-hide-details-hide-symlink-targets nil
	auto-save-list-file-prefix nil ; not create directory .emacs.d/auto-save-list
	;; Auto refresh dired, but be quiet about it
	global-auto-revert-non-file-buffers t
	wdired-allow-to-change-permissions t
	auto-revert-verbose nil
	auto-revert-interval 1
	delete-by-moving-to-trash t))
#+end_src
**** Doom Modeline
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
;; This changes the modeline bar at the bottom of the screen
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :config
  (setq doom-modeline-height 35      ;; sets modeline height
        doom-modeline-bar-width 5    ;; sets right bar width
        doom-modeline-persp-name t   ;; adds perspective name to modeline
        doom-modeline-persp-icon t   ;; adds folder icon next to persp name
	inhibit-compacting-font-caches t  ;; fix lagging issue
	))
#+end_src
**** Rainbow delimiters
Make parentheses different colors to easily tell how they close
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src
**** Dashboard
Landing page when opening Emacs. This contains some useful links (and it looks better than the default tutorial, or an empty scratch buffer)
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (use-package page-break-lines)
     (use-package dashboard
       :ensure t
       :init
       (setq initial-buffer-choice 'dashboard-open)
       ;; possible values: 'official, 'logo, integers (1, 2, 3, 4)
       (setq dashboard-startup-banner 2)
       (setq dashboard-set-heading-icons t)
       (setq dashboard-set-file-icons t)
       (setq dashboard-center-content t)
       (setq dashboard-vertically-center-content t)
       (setq dashboard-display-icons-p t)
       (setq dashboard-icon-type 'nerd-icons)
       (setq dashboard-filter-agenda-entry 'dashboard-no-filter-agenda)
       ;; choose which sections to show and how many items per section
       (setq dashboard-items '((recents   . 5)
                               (projects  . 5)
                               (agenda    . 5)
                               (bookmarks . 5)
                               (registers . 5)))
       ;; customize which widgets to display in order
       (setq dashboard-startupify-list '(dashboard-insert-banner
                                         ;; dashboard-insert-newline
                                         ;; dashboard-insert-banner-title
                                         ;; dashboard-insert-newline
                                         dashboard-insert-navigator
                                         dashboard-insert-newline
                                         dashboard-insert-init-info
                                         dashboard-insert-items
                                         dashboard-insert-newline
                                         dashboard-insert-footer))

       ;; customise the shortcuts for each heading on the dashboard
       (setq dashboard-item-shortcuts '((recents   . "r")
                                        (projects  . "p")
                                        (agenda    . "a")
                                        (bookmarks . "m")
                                        (registers . "e")))

       (setq dashboard-item-names '(("Agenda for the coming week:" . "Agenda:")))

       :config
       (dashboard-setup-startup-hook)
       )

     (setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")))
#+end_src
*** Treemacs
Using treemacs to show files in tree view on the left, to simulate an IDE experience such as Visual Studio Code
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (use-package treemacs
    :ensure t
    :defer t
    :init
    (with-eval-after-load 'winum
      (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
    :config
    (progn
      (setq treemacs-collapse-dirs                   (if treemacs-python-executable 3 0)
            treemacs-deferred-git-apply-delay        0.5
            treemacs-directory-name-transformer      #'identity
            treemacs-display-in-side-window          t
            treemacs-eldoc-display                   'simple
            treemacs-file-event-delay                2000
            treemacs-file-extension-regex            treemacs-last-period-regex-value
            treemacs-file-follow-delay               0.2
            treemacs-file-name-transformer           #'identity
            treemacs-follow-after-init               t
            treemacs-expand-after-init               t
            treemacs-find-workspace-method           'find-for-file-or-pick-first
            treemacs-git-command-pipe                ""
            treemacs-goto-tag-strategy               'refetch-index
            treemacs-header-scroll-indicators        '(nil . "^^^^^^")
            treemacs-hide-dot-git-directory          t
            treemacs-indentation                     2
            treemacs-indentation-string              " "
            treemacs-is-never-other-window           nil
            treemacs-max-git-entries                 5000
            treemacs-missing-project-action          'ask
            treemacs-move-files-by-mouse-dragging    t
            treemacs-move-forward-on-expand          nil
            treemacs-no-png-images                   nil
            treemacs-no-delete-other-windows         t
            treemacs-project-follow-cleanup          nil
            treemacs-persist-file                    (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
            treemacs-position                        'left
            treemacs-read-string-input               'from-child-frame
            treemacs-recenter-distance               0.1
            treemacs-recenter-after-file-follow      nil
            treemacs-recenter-after-tag-follow       nil
            treemacs-recenter-after-project-jump     'always
            treemacs-recenter-after-project-expand   'on-distance
            treemacs-litter-directories              '("/node_modules" "/.venv" "/.cask")
            treemacs-project-follow-into-home        nil
            treemacs-show-cursor                     nil
            treemacs-show-hidden-files               t
            treemacs-silent-filewatch                nil
            treemacs-silent-refresh                  nil
            treemacs-sorting                         'alphabetic-asc
            treemacs-select-when-already-in-treemacs 'move-back
            treemacs-space-between-root-nodes        t
            treemacs-tag-follow-cleanup              t
            treemacs-tag-follow-delay                1.5
            treemacs-text-scale                      nil
            treemacs-user-mode-line-format           nil
            treemacs-user-header-line-format         nil
            treemacs-wide-toggle-width               70
            treemacs-width                           35
            treemacs-width-increment                 1
            treemacs-width-is-initially-locked       t
            treemacs-workspace-switch-cleanup        nil)

      ;; The default width and height of the icons is 22 pixels. If you are
      ;; using a Hi-DPI display, uncomment this to double the icon size.
      ;;(treemacs-resize-icons 44)

      (treemacs-follow-mode t)
      (treemacs-filewatch-mode t)
      (treemacs-fringe-indicator-mode 'always)
      (when treemacs-python-executable
        (treemacs-git-commit-diff-mode t))

      (pcase (cons (not (null (executable-find "git")))
                   (not (null treemacs-python-executable)))
        (`(t . t)
         (treemacs-git-mode 'deferred))
        (`(t . _)
         (treemacs-git-mode 'simple)))

      (treemacs-hide-gitignored-files-mode nil))
    :bind
    (:map global-map
          ("M-0"       . treemacs-select-window)
          ("C-x t 1"   . treemacs-delete-other-windows)
          ("C-x t t"   . treemacs)
          ("C-x t d"   . treemacs-select-directory)
          ("C-x t B"   . treemacs-bookmark)
          ("C-x t C-t" . treemacs-find-file)
          ("C-x t M-t" . treemacs-find-tag)))

  (use-package treemacs-evil
    :after (treemacs evil)
    :ensure t)

  ;; Not using Projectile, so have commented this out
  ;; (use-package treemacs-projectile
  ;;   :after (treemacs projectile)
  ;;   :ensure t)

  (use-package treemacs-icons-dired
    :hook (dired-mode . treemacs-icons-dired-enable-once)
    :ensure t)

  (use-package treemacs-magit
    :after (treemacs magit)
    :ensure t)

  (use-package treemacs-persp ;;treemacs-perspective if you use perspective.el vs. persp-mode
    :after (treemacs persp-mode) ;;or perspective vs. persp-mode
    :ensure t
    :config (treemacs-set-scope-type 'Perspectives))

  (use-package treemacs-tab-bar ;;treemacs-tab-bar if you use tab-bar-mode
    :after (treemacs)
    :ensure t
    :config (treemacs-set-scope-type 'Tabs))
#+end_src
*** Which key
For more useful completion when you start typing a command
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (use-package which-key
    :init (which-key-mode)
    :diminish which-key-mode
    :config
    (setq which-key-idle-delay 0.5)
    (unbind-key "S-<left>" org-mode-map)
    (unbind-key "S-<right>" org-mode-map)
    (unbind-key "S-<up>" org-mode-map)
    (unbind-key "S-<down>" org-mode-map)
    (unbind-key "C-S-<left>" org-mode-map)
    (unbind-key "C-S-<right>" org-mode-map)
    (unbind-key "C-S-<up>" org-mode-map)
    (unbind-key "C-S-<down>" org-mode-map)
)
#+end_src
*** Org Mode
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package org
  :config
  (setq org-ellipsis " …")
  (setq org-log-done t))
#+end_src

Allows us to create a Table of Contents in our Org docs
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package toc-org
    :commands toc-org-enable
    :init (add-hook 'org-mode-hook 'toc-org-enable))
#+end_src

Better looking bullets rather than using default asterisks
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package org-bullets)
(add-hook 'org-mode-hook 'org-indent-mode)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
(electric-indent-mode -1)

(require 'org-tempo)

(use-package rainbow-mode
  :hook
  ((org-mode prog-mode) . rainbow-mode))

#+end_src

Org Roam and Agenda
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory "~/Notes")
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n i" . org-roam-node-insert))
  :config
  (org-roam-db-autosync-mode))

(setq org-agenda-files (list 
  "~/Notes/todo.org"
  "~/Notes/work.org"
  "~/Notes/home.org"))
#+end_src

Customise font sizes for org level headers
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(custom-set-faces
 '(org-level-1 ((t (:inherit outline-1 :height 1.2))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.1))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.05))))
 '(org-level-4 ((t (:inherit outline-4 :height 1.0))))
 '(org-level-5 ((t (:inherit outline-5 :height 1.0))))
 '(org-level-6 ((t (:inherit outline-5 :height 1.0))))
 '(org-level-7 ((t (:inherit outline-5 :height 1.0)))))
#+end_src

Org modern 
FIXME Does not load. when evaluated manually, issues with the bullets not showing as expected.
Also issues with links showing inline with headings when collapsed. 
#+begin_src emacs-lisp
(use-package org-modern)
(with-eval-after-load 'org (global-org-modern-mode))
#+end_src

*** CSV Mode
To make editing csv files easier. This tabulates the contents in a csv file to algin the columns.
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (use-package csv-mode
    :ensure t
    :hook (csv-mode . csv-align-mode))
#+end_src
*** Magit
Git management tool
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  ;; Git porcelain (porcelain = make it nice)
  ;; Main control is C-x g
  (use-package magit
    :ensure t
    :config
    (setq magit-save-repository-buffers nil))
#+end_src
*** Company
*what does company do?*
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package company
  :ensure t
  :hook (after-init . global-company-mode)
  :custom
  ;; Search other buffers with the same major mode for completion.
  (company-dabbrev-other-buffers t)
  (company-dabbrev-code-other-buffers t)
  ;; M-<num> to select an option according to its number.
  (company-show-numbers t)
  ;; Only 2 letters required for completion to activate.
  (company-minimum-prefix-length 2)
  ;; Do not downcase completions by default.
  (company-dabbrev-downcase nil)
  ;; Even if I write something with the wrong case,
  ;; provide the correct casing.
  (company-dabbrev-ignore-case t)
  ;; Company completion wait time.
  (company-idle-delay 0.2)
  ;; Disable company-mode in shell and eshell modes.
  (company-global-modes '(not eshell-mode shell-mode)))

(use-package company-box
    :hook (company-mode . company-box-mode))
#+end_src
*** Evil Mode
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(unless (package-installed-p 'evil)
  (package-install 'evil))

;; Install Evil and disable C-i to jump forward to restore TAB functionality in Org mode.
(use-package evil
  :ensure t
  :init 
  (setq evil-want-C-i-jump nil)
  (setq evil-want-keybinding nil)
  :config (evil-mode 1))

(use-package evil-collection
  :after evil
  :ensure t
  :config
  (evil-collection-init))

(defun my-org-mode-insert-tab ()
  "Insert a literal tab character in Insert mode."
  (interactive)
  (insert "\t"))

(defun my-org-mode-cycle ()
  "Cycle through headings in Normal and other states."
  (interactive)
  (org-cycle))

;; FIXME Shift-selection not working in insert mode. Current workaround to use visual mode
(defun my-insert-mode-shift-selection ()
  "Enable Shift-selection in Insert mode."
  (define-key evil-insert-state-map (kbd "S-<left>") 'my-shift-select-left)
  (define-key evil-insert-state-map (kbd "S-<right>") 'my-shift-select-right)
  (define-key evil-insert-state-map (kbd "S-<up>") 'my-shift-select-up)
  (define-key evil-insert-state-map (kbd "S-<down>") 'my-shift-select-down))

(defun my-shift-select-left ()
  "Extend selection to the left in Insert mode."
  (interactive)
  (if (use-region-p)
      (setq deactivate-mark nil)
    (set-mark (point)))
  (backward-char))

(defun my-shift-select-right ()
  "Extend selection to the right in Insert mode."
  (interactive)
  (if (use-region-p)
      (setq deactivate-mark nil)
    (set-mark (point)))
  (forward-char))

(defun my-shift-select-up ()
  "Extend selection upwards in Insert mode."
  (interactive)
  (if (use-region-p)
      (setq deactivate-mark nil)
    (set-mark (point)))
  (previous-line))

(defun my-shift-select-down ()
  "Extend selection downwards in Insert mode."
  (interactive)
  (if (use-region-p)
      (setq deactivate-mark nil)
    (set-mark (point)))
  (next-line))

(defun my-org-mode-setup ()
  "Custom setup for Org mode with Evil mode."
  (when (derived-mode-p 'org-mode)
    ;; Bind `TAB` to `my-org-mode-insert-tab` and `my-org-mode-cycle`
    (evil-define-key 'insert org-mode-map (kbd "TAB") 'my-org-mode-insert-tab)
    (evil-define-key 'normal org-mode-map (kbd "TAB") 'my-org-mode-cycle)
    (evil-define-key 'visual org-mode-map (kbd "TAB") 'my-org-mode-cycle)
    ;; Set up Shift-selection in Insert mode
    (my-insert-mode-shift-selection)))

(add-hook 'org-mode-hook 'my-org-mode-setup)

;; Ensure transient-mark-mode is enabled for highlighting selections
(transient-mark-mode 1)
#+end_src
*** Development Environments
**** Python setup
`python.el' provides `python-mode' which is the builtin major-mode for the Python language.
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package python
  :config
  ;; Remove guess indent python message
  (setq python-indent-guess-indent-offset-verbose nil))
#+end_src

Numpy style docstring for Python. See: https://github.com/douglasdavis/numpydoc.el.
There are other packages available for docstrings, see: https://github.com/naiquevin/sphinx-doc.el
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package numpydoc
  :ensure t
  :defer t
  :custom
  (numpydoc-insert-examples-block nil)
  (numpydoc-template-long nil)
  :bind (:map python-mode-map
              ("C-c C-n" . numpydoc-generate)))
#+end_src
**** Poetry (Python development)
Install the Poetry package for Python development. See [[https://python-poetry.org/docs/][Poetry Documentation]].
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package poetry
  :ensure t
  :defer t
  :config
  ;; Checks for the correct virtualenv. Better strategy IMO because the default
  ;; one is quite slow.
  (setq poetry-tracking-strategy 'switch-buffer)
:hook (python-mode . poetry-tracking-mode))
#+end_src
**** Eglot - Language Server Protocol
Package for Language Server Protocol support. Useful for coding in different languages. Has some autocompletion features. Another alternative package is LSP mode. I have not used it, but apparently eglot is more minimal.
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package eglot
  :ensure t
  :defer t
  :hook (python-mode . eglot-ensure))

;; Don't blow out the minibuffer with company
(setq eldoc-echo-area-use-multiline-p nil)

;; Some extra python fluff TODO does this need to go into the python setup section above?
(add-hook 'python-mode-hook (lambda () (setq fill-column 120)))

;; Allows eglot to always find your python env when set with pyenv or poetry
;; config stolen from github page
(use-package pet
  ;:ensure-system-package (dasel sqlite3)
  :config
  (add-hook 'python-mode-hook
            (lambda ()
              (setq-local python-shell-interpreter (pet-executable-find "python")
                          python-shell-virtualenv-root (pet-virtualenv-root))

              (pet-eglot-setup)
              (eglot-ensure)

              (setq-local lsp-jedi-executable-command
                         (pet-executable-find "jedi-language-server")))))
#+end_src
**** Pyright (LSP)
NOTE: Why do we need both Eglot AND Pyright? What is the difference? I have also heard of tree-sitter which is apparently good. See: https://www.adventuresinwhy.com/post/eglot/
FIXME check if I actually need this exec-path line. I got it from https://www.adventuresinwhy.com/post/eglot/
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package exec-path-from-shell
  :ensure t
  :config
  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize)))

(use-package lsp-pyright
  :ensure t
  :defer t
  ;; Launches pyright when a python buffer is opened.
  :hook ((python-mode . (lambda ()
			  (require 'lsp-pyright)
                         (lsp)))))
#+end_src
**** Black - Code Formatting
Buffer formatting on save using black.
See: https://github.com/pythonic-emacs/blacken.
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package blacken
  :ensure t
  :defer t
  :custom
  (blacken-allow-py36 t)
  (blacken-skip-string-normalization t)
  :hook (python-mode-hook . blacken-mode))
#+end_src
*** Custom functions
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
  (defun reload-init-file ()
    (interactive)
    (load-file user-init-file))
#+end_src
*** Global keybindings
#+begin_src emacs-lisp :tangle "config.el" :mkdirp yes
(use-package general)

(define-key global-map "\C-cl" 'org-store-link)
  (define-key global-map "\C-ca" 'org-agenda)

(general-define-key
 "C-M-j" 'counsel-switch-buffer
 "C-x r C-f" 'counsel-recentf
 "C-M-i" '(lambda () (interactive) (find-file user-init-file))
 "C-c l" 'org-store-link
 "C-c a" 'org-agenda
 "C-c C-/" 'comment-or-uncomment-region

 ;; Use ESC to quit prompts (same as C-q)
 "<escape>" 'keyboard-escape-quit

 ;; You can use the bindings CTRL plus =/- for zooming in/out.  You can also use CTRL plus the mouse wheel for zooming in/out.
 "C-=" 'text-scale-increase
 "C--" 'text-scale-decrease
 "<C-wheel-up>" 'text-scale-increase
 "<C=wheel-down>" 'text-scale-decrease
)
#+end_src
